#!/bin/bash
cd /home/ec2-user/ruby-on-rails
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm requirements
rvm install 2.3.0
gem install rails
bundle install
grep SECRET_KEY_BASE $HOME/.bashrc || echo "export SECRET_KEY_BASE=`rake secret`" >> $HOME/.bashrc && source $HOME/.bashrc
RAILS_ENV=production
bundle exec rake assets:precompile
bundle exec passenger start -p 80 -d -e production
